{
 "title": "Homebrew Club",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperatures",
   "type": "graph",
   "description": "Changed to null values from \"null\" to \"connected\" temporarily",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Glycol Chiller Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperatures",
     "query": "SELECT mean(\"glycol\"), mean(\"GLYCOL\") FROM \"temperatures\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "GLYCOL" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Ambient Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperatures",
     "query": "SELECT mean(\"ambient\") FROM \"temperatures\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "AMBIENT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Glycol Temperature Setpoint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "setpoints",
     "select": [
      [
       { "params": [ "GLYCOL" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outputs",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Glycol Output Active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "outputs",
     "query": "SELECT mean(\"glycolActive\")  * 5 FROM \"outputs\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "GLYCOL" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "errors",
     "select": [
      [
       { "params": [ "exceptionType" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Glycol Chiller Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperatures",
     "query": "SELECT \"GLYCOL\" FROM \"temperatures\" ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "GLYCOL" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}